import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import {
  FaFacebookF,
  FaLinkedinIn,
  FaGoogle,
  FaRegEnvelope,
} from "react-icons/fa";

import { MdLockOutline } from "react-icons/md";

export default function Home() {
  return (
    <div className={styles.container + " bg-gray-200"}>
      <Head>
        <title>Msus Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main + " text-center"}>
        <div className="flex bg-white flex-wrap-reverse rounded-2xl w-full lg:w-3/5 lg:max-w-4xl shadow-2xl">
          <div className="lg:w-3/5 p-3 w-full  lg:p-5">
            <div className="text-left font-bold">
              <span className="text-green-500">Msus</span>Coorporation
            </div>
            <div className="py-10">
              <h2 className="text-3xl font-bold text-green-500 mb-2">
                S &apos; incrire à son compte
              </h2>
              <div className="border-2 border-green-500 w-10 mx-auto mb-2"></div>
              <div className="flex justify-center space-x-1 my-2">
                <a
                  href=""
                  className="border-2 border-gray-200 rounded-full p-2"
                >
                  <FaFacebookF className="text-sm" />
                </a>
                <a
                  className="border-2 border-gray-200 rounded-full p-2"
                  href=""
                >
                  <FaLinkedinIn className="text-sm" />
                </a>
                <a
                  className="border-2 border-gray-200 rounded-full p-2"
                  href=""
                >
                  <FaGoogle className="text-sm" />
                </a>
              </div>
              {/** Social media icon */}
              <p className="text-gray-400 my-3">or use your email account</p>
              <div className="flex flex-col items-center space-y-3">
                <div className="bg-gray-100 flex items-center space-x-2 p-2 sm:w-64">
                  <FaRegEnvelope className="text-gray-400" />
                  <input
                    type="text"
                    name="email"
                    className="bg-inherit outline-none text-sm flex-1"
                    placeholder="Email"
                  />
                </div>
                <div className="bg-gray-100 flex items-center space-x-2 p-2  sm:w-64">
                  <MdLockOutline className="text-gray-400" />
                  <input
                    type="password"
                    name="password"
                    className="bg-inherit outline-none text-sm flex-1"
                    placeholder="Password"
                  />
                </div>
                <div className="flex justify-between w-64">
                  <label className="space-x-1 flex items-center text-xs">
                    <input type="checkbox" className="" />
                    <span>Se rappeler de moi</span>
                  </label>
                  <a href="" className="text-xs ">
                    Mot de passe oublié{" "}
                  </a>
                </div>
                <a
                  href=""
                  className="border-2 border-green-500 text-green-500 px-12 py-2 rounded-full inline-block font-semibold hover:bg-green-500 hover:text-white"
                >
                  Se connecter
                </a>
              </div>
            </div>
          </div>{" "}
          {/** Partie de login */}
          <div className="lg:w-2/5 w-full bg-emerald-500 rounded-r-2xl text-white py-36 lg:px-12">
            <h2 className="text-3xl font-bold mb-2">Bienvenue amis!</h2>
            <div className="border-2 border-white w-10 mx-auto mb-2"></div>
            <p className="mb-10">
              Remplit tes informations personnelles et débute la journée avec
              nous.
            </p>
            <a
              href=""
              className="border-2 border-white px-12 py-2 rounded-full inline-block font-semibold hover:bg-white hover:text-green-500"
            >
              S &apos; incrire
            </a>
          </div>
          {/** Partie de créationd e compte */}
        </div>
      </main>
    </div>
  );
}
